// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ehuf82rzdc","name":"sampleCloudApi","description":"","endpoint":"https://ehuf82rzdc.execute-api.us-east-2.amazonaws.com/Development","region":"us-east-2","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-2:7ceb24a4-0977-4774-bf6a-e1f9f622532c',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'memepie-hosting-mobilehub-2114693465',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd26nxxu4ntueoe.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-2',
    'aws_dynamodb_table_schemas': [{"tableName":"memepie-mobilehub-2114693465-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-2","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': 'e41d45765d1f443eb6df1ad3bf72fac9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ebff12bd-5031-4f6d-990d-2648fa8d91c0',
    'aws_project_name': 'memePie2.0-2018-07-11-13-15-38',
    'aws_project_region': 'us-east-2',
    'aws_resource_bucket_name': 'memepie-deployments-mobilehub-2114693465',
    'aws_resource_name_prefix': 'memepie-mobilehub-2114693465',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'memepie-userfiles-mobilehub-2114693465',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_iBSmdO7lZ',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4tnen8jo21v6950hl05uekg3vu',
    'aws_appsync_graphqlEndpoint': 'https://6o3lfbcsjrgylisaoqdnpusfza.appsync-api.us-east-2.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-2',
    'aws_appsync_authenticationType': 'AWS_IAM',
}

export default awsmobile;
